version: "2.1"

services:
  backend:
    image: blog-backend
    build:
      context: .
    ports:
      - "8000:8000"
  frontend:
    image: blog-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
