version: "2.1"

services:
  backend:
    image: blog-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    image: blog-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
