version: "2.1"

services:
  backend:
    image: blog-backend
    build:
      context: ./backend
    ports:
      - "5000:80"
  frontend:
    image: blog-frontend
    build:
      context: ./frontend
    ports:
      - "8080:80"
